### ISSUE TITLE
Fix Trip pagination

### ISSUE THREAD

**Issue by shayneo** [vinli/ios-net#18]

**Comment by shayneo** [comment]
@tommista @bryanOrtiz just creating this to keep tabs on the issue

**Comment by aneena-thomas** [comment]
Is that issue fixed?

**Comment by shayneo** [comment]
Hey @aneena-thomas this is currently being worked on! This ticket will be updated once the fix is made.

**Comment by bryanOrtiz** [comment]
Hey @aneena-thomas this issue should now be fixed with the latest version 1.1.3. Thanks for bringing this to our attention!

**Comment by aneena-thomas** [comment]
ok.i will check before that i have doubt how to update Vinlinet into 1.1.3 through cocoapods?

**Comment by bryanOrtiz** [comment]
If cocoapods is properly installed on your machine, you should be able to update it through the terminal.

All you have to do is go to the root-directory of your projects repository through the terminal and then type the command:

pod update

See documentation for more info.  <https://guides.cocoapods.org/using/pod-install-vs-update.html>

**Comment by aneena-thomas** [comment]
already done it.anyway thanks
