### ISSUE TITLE
Implement Diagnostic Service

### ISSUE THREAD

**Issue by andrewwells** [vinli/ios-net#4]
Implement Diagnostic Service

**Comment by shayneo** [comment]
@dofchinick just realized this has been hanging out here for a while. Would be great to get it into an upcoming sprint.

**Comment by dofchinick** [comment]
@shayneo - Rgr that.  We just locked down Sprint 6 yesterday, but I'll put this on the backlog list for candidates for next sprint (starts 11/3).

**Comment by DiegoResnik** [comment]
Is it in?

**Comment by DiegoResnik** [comment]
@dofchinick / @shayneo any progress on this issue?

**Comment by shayneo** [comment]
@DiegoResnik it's being worked on now! Stay tuned 😸

**Comment by shayneo** [comment]
@DiegoResnik this is done! just update your cocoapod
